# Uncomment the next line to define a global platform for your project
# platform :ios, '17.0'

target 'Snapkit' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods
  pod 'SnapKit', '~> 5.7.0'
  pod 'Then'
  pod 'Kingfisher'
end
