//
//  PostListModels.swift
//  dynamic_table_view_tutorial
//
//  Created by 김동현 on 3/31/25.
//  Copyright (c) 2025 Tuentuenna. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum PostList
{
    // MARK: Use cases
    
    enum FetchPostList
    {
        struct Request // 뷰 -> 인터렉터한테 요청하는 데이터
        {
            var count: Int = 10
        }
        struct Response // 워커에서 들어온 데이터
        {
            var posts: [Post]
        }
        struct ViewModel // 프리젠터 -> 뷰에 전달하는 데이터
        {
            
        }
    }
}
