//
//  PostListInteractor.swift
//  dynamic_table_view_tutorial
//
//  Created by 김동현 on 3/31/25.
//  Copyright (c) 2025 Tuentuenna. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol PostListBusinessLogic
{
    func fetchPostList(request: PostList.Something.Request)
}

protocol PostListDataStore
{
    //var name: String { get set }
}

class PostListInteractor: PostListBusinessLogic, PostListDataStore
{
    var presenter: PostListPresentationLogic?
    var worker: PostListWorker?
    //var name: String = ""
    
    // MARK: Do something
    
    func doSomething(request: PostList.Something.Request)
    {
        worker = PostListWorker()
        worker?.doSomeWork()
        
        let response = PostList.Something.Response()
        presenter?.presentSomething(response: response)
    }
}
